routes/web.php
<?php

Route::get('', 'IndexController@index')->name('home');
Route::get('location/{location}', 'IndexController@location')->name('location');

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'middleware' => 'auth'], function(){
    Route::get('', 'ProfileController@index')->name('index');
    Route::get('error', 'ProfileController@error')->name('error');

    Route::post('password/add/{user}', 'ProfileController@addPassword')->name('password.add');
    Route::post('password/change/{user}', 'ProfileController@changePassword')->name('password.change');
});

Route::post('location/{location}/change', 'IndexController@changeLocation')->name('location.change');

Route::post('login', 'IndexController@login')->name('login');

Route::get('logout', 'IndexController@logout')->name('logout');

Route::get('register', 'IndexController@register')->name('register');
Route::post('register', 'IndexController@saveRegistrar')->name('save_registrar');

Route::group(['prefix' => 'pipe', 'as' => 'pipe.', 'middleware' => 'pipe_admin'], function(){
    Route::post('modify/{pipe}/{location}', 'PipeController@modify')->name('modify');
    Route::post('add/{location}', 'PipeController@add')->name('add');
    Route::post('delete/{pipe}/{location}', 'PipeController@delete')->name('delete');
});

Route::group(['prefix' => 'admin/', 'as' => 'admin.', 'middleware' => 'admin'], function(){
    Route::get('', 'AdminController@index')->name('index');

    Route::get('regs', 'AdminController@regs')->name('regs');
    Route::post('regs/delete/{reg}', 'AdminController@deleteReg')->name('regs.delete');
    Route::post('regs/accept/{reg}', 'AdminController@acceptReg')->name('regs.accept');

    Route::get('pipes', 'AdminController@pipes')->name('pipes');

    Route::get('pipes/{pipe}', 'AdminController@showPipe')->name('pipe.show');
    Route::post('pipes/delete/{pipe}', 'AdminController@deletePipe')->name('pipe.delete');

    Route::group(['prefix' => 'locations', 'as' => 'locations.'], function(){
        Route::get('locations', 'AdminController@locations')->name('index');
        Route::get('{location}', 'AdminController@showLocation')->name('show');

        Route::post('delete/location/{location}', 'AdminController@deleteLocation')->name('delete');
        Route::post('add', 'AdminController@addLocation')->name('add');

        Route::post('delete/admin/{user}/location/{location}', 'AdminController@deleteAdmin')->name('delete_admin');
        Route::post('add/admin/location/{location}', 'AdminController@addAdmin')->name('add_admin');
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
        Route::get('', 'UsersController@index')->name('index');

        Route::post('delete/{user}', 'UsersController@delete')->name('delete');
        Route::post('admin/remove/{user}', 'UsersController@removeSuperAdmin')->name('remove_super_admin');
        Route::post('admin/add/{user}', 'UsersController@addSuperAdmin')->name('add_super_admin');
    });
});

resources/views/home/index.blade.php
@extends('layouts.main')

@section('title', 'Főoldal')

@section('content')
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="text-align:center;">
                <a class="panel-title" data-toggle="collapse" href="#locations" style="text-align:center; width:100%; color:white;">
                    {{ $current_location->name }} - {{ $current_location->description }} &#x25BC;
                </a>
            </div>
            <div class="panel-collapse collapse" id="locations">
                <ul class="nav">
                    @foreach($locations as $location)
                        @if(!$location->hidden)
                            <li style="text-align:center;">
                                <a href="{{ route('location', [$location]) }}">{{ $location->name }} - {{ $location->description }}</a>
                            </li>
                        @endif
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    @if($admin)
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Jelenlegi felszereltség</h3>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>Dohány</th>
                            <td>{{ $current_location->getTobaccoState() }} ({{ $current_location->tobacco_type }})</td>
                        </tr>
                        <tr>
                            <th>Szén</th>
                            <td>{{ $current_location->getCoalState() }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Jelenlegi pipa</h3>
                </div>
                @if($current_pipe != null)
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>Dohány</th>
                            <td>{{ $current_pipe->type }}</td>
                        </tr>
                        <tr>
                            <th>Állapot</th>
                            <td>{{ $current_status }}</td>
                        </tr>
                    </table>
                </div>
                @else
                <div class="panel-body">
                    Jelenleg nincs pipa
                </div>
                @endif
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Pipadmin</h3>
                </div>
                <div class="panel-body">
                    @if($current_pipe != null)
                    <form id="pipe-form" action="{{ route('pipe.modify', [$current_pipe, $current_location]) }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <div class="input-group">
                                <label class="input-group-addon" for="type">Dohány</label>
                                <input class="form-control" name="type" id="type" value="{{ $current_pipe->type }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <label class="input-group-addon" for="status">Állapot</label>
                                <select class="form-control" name="status" id="status">
                                    <option value="starting" @if($current_status == "Készül") selected @endif>Készül</option>
                                    <option value="good" @if($current_status == "Jó") selected @endif>Jó</option>
                                    <option value="dying" @if($current_status == "Kezd meghalni") selected @endif>Kezd meghalni</option>
                                    <option value="dead">Meghalt</option>
                                </select>
                            </div>
                        </div>
                    </form>
                    @else
                        <form id="pipe-form" action="{{ route('pipe.add', [$current_location]) }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <div class="input-group">
                                    <label class="input-group-addon" for="type">Dohány</label>
                                    <input class="form-control" name="type" id="type">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <label class="input-group-addon" for="status">Állapot</label>
                                    <select class="form-control" name="status" id="status">
                                        <option value="starting">Készül</option>
                                        <option value="good">Jó</option>
                                        <option value="dying">Kezd meghalni</option>
                                    </select>
                                </div>
                            </div>
                        </form>
                    @endif
                </div>
                <div class="panel-footer">
                    <input type="button" onclick="document.getElementById('pipe-form').submit()" value="Mentés" class="btn btn-primary">
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Dohadmin</h3>
                </div>
                <div class="panel-body">
                    <form id="change-location" action="{{ route('location.change', $current_location) }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <div class="input-group">
                                <label for="coal" class="input-group-addon">Szén</label>
                                <select class="form-control" id="coal" name="coal">
                                    <option value="0" @if($current_location->coal == 0) selected @endif>Nincs</option>
                                    <option value="1" @if($current_location->coal == 1) selected @endif>Fogyóban</option>
                                    <option value="2" @if($current_location->coal == 2) selected @endif>Van</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <label for="tobacco" class="input-group-addon">Dohány</label>
                                <select class="form-control" id="tobacco" name="tobacco">
                                    <option value="0" @if($current_location->tobacco == 0) selected @endif>Nincs</option>
                                    <option value="1" @if($current_location->tobacco == 1) selected @endif>Fogyóban</option>
                                    <option value="2" @if($current_location->tobacco == 2) selected @endif>Van</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <label for="tobacco-type" class="input-group-addon">Dohány típus</label>
                                <input id="tobacco-type" class="form-control" name="tobacco_type" value="{{ $current_location->tobacco_type }}">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <button type="submit" class="btn btn-default" form="change-location">Mentés</button>
                </div>
            </div>
        </div>
    @else
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Jelenlegi felszereltség</h3>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>Dohány</th>
                            <td>{{ $current_location->getTobaccoState() }} ({{ $current_location->tobacco_type }})</td>
                        </tr>
                        <tr>
                            <th>Szén</th>
                            <td>{{ $current_location->getCoalState() }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Jelenlegi pipa</h3>
                </div>
                @if($current_pipe != null)
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>Dohány</th>
                            <td>{{ $current_pipe->type }}</td>
                        </tr>
                        <tr>
                            <th>Állapot</th>
                            <td>{{ $current_status }}</td>
                        </tr>
                    </table>
                </div>
                @else
                <div class="panel-body">
                    Nincs jelenleg pipa
                </div>
                @endif
            </div>
        </div>
    @endif
@endsection

resources/views/home/profile.blade.php
@extends('layouts.main')

@section('title', 'Profil')

@section('content')
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ $user->name }}</h3>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Felhasználónév</th>
                        <td>{{ $user->username }}</td>
                    </tr>
                    <tr>
                        <th>Név</th>
                        <td>{{ $user->name }}</td>
                    </tr>
                    <tr>
                        <th>Csatlakozott</th>
                        <td>{{ $user->created_at->diffForHumans() }}</td>
                    </tr>
                    @if($user->locations->count() != 0)
                        <tr>
                            <th>Pipák száma</th>
                            <td>{{ $user->pipes->count() }}</td>
                        </tr>
                    @endif
                    <tr>
                        <th>AuthSCH</th>
                        <td>@if($user->authsch_id!=null) <i class="fa fa-check"></i> @else <i class="fa fa-times"></i> @endif</td>
                    </tr>
                    <tr>
                        <th>Jelszavas belépés</th>
                        <td>@if($user->password!=null) <i class="fa fa-check"></i> @else <i class="fa fa-times"></i> @endif</td>
                    </tr>
                </table>
            </div>
            <div class="panel-footer">
                @if($user->password == null)
                    <button class="btn btn-default" data-toggle="modal" data-target="#add-password">Jelszó hozzáadása</button>
                @else
                    <button class="btn btn-default" data-toggle="modal" data-target="#change-password">Jelszó módosítása</button>
                @endif
            </div>
        </div>
    </div>
@endsection

@section('modals')
    @if($user->password == null)
    <div class="modal fade" role="dialog" id="add-password">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">Jelszó hozzáadása</h3>
                </div>
                <div class="modal-body">
                    <form id="add-password-form" action="{{ route('profile.password.add', [$user]) }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <div class="input-group">
                                <label class="input-group-addon" for="password1">Jelszó</label>
                                <input type="password" class="form-control" id="password1" name="password1">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <label class="input-group-addon" for="password2">Jelszó mégegyszer</label>
                                <input type="password" class="form-control" id="password2" name="password2">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" type="button">Mégse</button>
                    <button class="btn btn-primary" form="add-password-form">Mentés</button>
                </div>
            </div>
        </div>
    </div>
    @else
        <div class="modal fade" role="dialog" id="change-password">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h3 class="modal-title">Jelszó módosítása</h3>
                    </div>
                    <div class="modal-body">
                        <form id="add-password-form" action="{{ route('profile.password.change', [$user]) }}" method="POST">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <div class="input-group">
                                    <label class="input-group-addon" for="password_old">Régi jelszó</label>
                                    <input type="password" class="form-control" id="password_old" name="password_old">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <label class="input-group-addon" for="password1">Jelszó</label>
                                    <input type="password" class="form-control" id="password1" name="password1">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <label class="input-group-addon" for="password2">Jelszó mégegyszer</label>
                                    <input type="password" class="form-control" id="password2" name="password2">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" type="button">Mégse</button>
                        <button class="btn btn-primary" form="add-password-form">Mentés</button>
                    </div>
                </div>
            </div>
        </div>
    @endif
@endsection

@section('scripts')
    @if(isset($error))
        <script>
            $('#add-password').modal().open();
            $('#change-password').modal().open();
        </script>
    @endif
@endsection

resources/views/home/register.blade.php
@extends('layouts.main')

@section('title', 'Felhasználónév igénylés')

@section('content')
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Felhasználó igénylése</h3>
            </div>
            <div class="panel-body">
                <form action="{{ route('save_registrar') }}" method="POST" id="register-form">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <div class="input-group">
                            <label class="input-group-addon" for="name">Teljes név</label>
                            <input class="form-control" name="name" id="name">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <label class="input-group-addon" for="email">Email cím</label>
                            <input type="email" class="form-control" name="email" id="email">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <label class="input-group-addon" for="username">Kívánt felhasználónév</label>
                            <input class="form-control" id="username" name="username">
                        </div>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <a href="#" onclick="document.getElementById('register-form').submit()" class="btn btn-default">Küldés</a>
            </div>
        </div>

        @if(isset($error))
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        @switch($error)
                            @case('email')
                                Email already in use
                            @break
                        @endswitch
                    </h3>
                </div>
            </div>
        @endif
    </div>
@endsection