routes/web.php
<?php

Route::get('', 'IndexController@index')->name('home');
Route::get('location/{location}', 'IndexController@location')->name('location');

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'middleware' => 'auth'], function(){
    Route::get('', 'ProfileController@index')->name('index');
    Route::get('error', 'ProfileController@error')->name('error');

    Route::post('password/add/{user}', 'ProfileController@addPassword')->name('password.add');
    Route::post('password/change/{user}', 'ProfileController@changePassword')->name('password.change');
});

Route::post('location/{location}/change', 'IndexController@changeLocation')->name('location.change');

Route::post('login', 'IndexController@login')->name('login');

Route::get('logout', 'IndexController@logout')->name('logout');

Route::get('register', 'IndexController@register')->name('register');
Route::post('register', 'IndexController@saveRegistrar')->name('save_registrar');

Route::group(['prefix' => 'pipe', 'as' => 'pipe.', 'middleware' => 'pipe_admin'], function(){
    Route::post('modify/{pipe}/{location}', 'PipeController@modify')->name('modify');
    Route::post('add/{location}', 'PipeController@add')->name('add');
    Route::post('delete/{pipe}/{location}', 'PipeController@delete')->name('delete');
});

Route::group(['prefix' => 'admin/', 'as' => 'admin.', 'middleware' => 'admin'], function(){
    Route::get('', 'AdminController@index')->name('index');

    Route::get('regs', 'AdminController@regs')->name('regs');
    Route::post('regs/delete/{reg}', 'AdminController@deleteReg')->name('regs.delete');
    Route::post('regs/accept/{reg}', 'AdminController@acceptReg')->name('regs.accept');

    Route::get('pipes', 'AdminController@pipes')->name('pipes');

    Route::get('pipes/{pipe}', 'AdminController@showPipe')->name('pipe.show');
    Route::post('pipes/delete/{pipe}', 'AdminController@deletePipe')->name('pipe.delete');

    Route::group(['prefix' => 'locations', 'as' => 'locations.'], function(){
        Route::get('locations', 'AdminController@locations')->name('index');
        Route::get('{location}', 'AdminController@showLocation')->name('show');

        Route::post('delete/location/{location}', 'AdminController@deleteLocation')->name('delete');
        Route::post('add', 'AdminController@addLocation')->name('add');

        Route::post('delete/admin/{user}/location/{location}', 'AdminController@deleteAdmin')->name('delete_admin');
        Route::post('add/admin/location/{location}', 'AdminController@addAdmin')->name('add_admin');
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function(){
        Route::get('', 'UsersController@index')->name('index');

        Route::post('delete/{user}', 'UsersController@delete')->name('delete');
        Route::post('admin/remove/{user}', 'UsersController@removeSuperAdmin')->name('remove_super_admin');
        Route::post('admin/add/{user}', 'UsersController@addSuperAdmin')->name('add_super_admin');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'password', 'super_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function pipes()
    {
        return $this->hasMany(Pipe::class,'created_by');
    }

    public function locations()
    {
        return $this->belongsToMany(Location::class, 'user_location','user_id','location_id');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::all();

        Carbon::setLocale('hu');

        return view('admin.users.index', ['users' => $users]);
    }

    public function delete(User $user)
    {
        if($user->id == Auth::user()->id){
            abort(418);
        }

        foreach($user->locations as $location){
            $location->admins()->detach($user->id);
        }
        foreach($user->pipes as $pipe){
            $pipe->created_by = 0;
        }
        $user->delete();

        return redirect()->route('admin.users.index');
    }

    public function removeSuperAdmin(User $user){
        $user->super_admin = 0;
        $user->save();

        return redirect()->back();
    }

    public function addSuperAdmin(User $user){
        $user->super_admin = 1;
        $user->save();

        return redirect()->back();
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('title', 'Felhasználók')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Felhasználók</h3>
        </div>
        <div class="table-responsive">
            <table class="table table-striped" id="users-table">
                <thead>
                <tr>
                    <th>Felhasználónév</th>
                    <th>Név</th>
                    <th>Email cím</th>
                    <th>AuthSCH-s belépés</th>
                    <th>Jelszavas belépés</th>
                    <th>Csatlakozott</th>
                    <th>Műveletek</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->username }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>@if($user->authsch_id != null) <i class="fa fa-check"></i> @else <i class="fa fa-times"></i> @endif</td>
                        <td>@if($user->password != null) <i class="fa fa-check"></i> @else <i class="fa fa-times"></i> @endif</td>
                        <td>{{ $user->created_at->diffForHumans() }}</td>
                        <td>
                            @if($user->id != Auth::user()->id)
                            <span data-toggle="tooltip" title="Törlés">
                                <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-user-{{ $user->id }}">
                                    <i class="fa fa-times"></i>
                                </button>
                            </span>
                                @if($user->super_admin)
                                <form style="display:none;" method="POST" action="{{ route('admin.users.remove_super_admin', $user) }}" id="super-admin-{{ $user->id }}">{{ csrf_field() }}</form>
                                <span data-toggle="tooltip" title="Admin jogosultság megvonása">
                                    <button class="btn btn-sm btn-primary" form="super-admin-{{ $user->id }}">
                                        <i class="fa fa-user"></i>
                                    </button>
                                </span>
                                @else
                                <form style="display:none;" method="POST" action="{{ route('admin.users.add_super_admin', $user) }}" id="super-admin-{{ $user->id }}">{{ csrf_field() }}</form>
                                    <span data-toggle="tooltip" title="Admin jogosultság megadása">
                                    <button class="btn btn-sm btn-default" form="super-admin-{{ $user->id }}">
                                        <i class="fa fa-user-o"></i>
                                    </button>
                                </span>
                                @endif
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th>Felhasználónév</th>
                    <th>Név</th>
                    <th>Email cím</th>
                    <th>AuthSCH-s belépés</th>
                    <th>Jelszavas belépés</th>
                    <th>Csatlakozott</th>
                    <th>Műveletek</th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@section('modals')
    @foreach($users as $user)
        <div class="modal fade" role="dialog" id="delete-user-{{ $user->id }}">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h3 class="modal-title">Felhasználó törlése</h3>
                    </div>
                    <div class="modal-body">
                        <h4>Biztosan törlöd ezt a felhasználót?</h4>
                        <p>Név: {{ $user->name }}</p>
                        <p>Felhasználónév: {{ $user->username }}</p>
                        <p>Email: {{ $user->email }}</p>
                        <p>Adminja: @foreach($user->locations as $location) {{ $location->name }}, @endforeach</p>
                    </div>
                    <div class="modal-footer">
                        <form action="{{ route('admin.users.delete', $user) }}" method="POST">
                            {{ csrf_field() }}
                            <button class="btn btn-danger">Igen</button>
                            <button class="btn btn-default" data-dismiss="modal" type="button">Nem</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    @endforeach
@endsection

@section('scripts')
    <script>
        $('#users-table').dataTable();
        $('[data-toggle="tooltip"]').tooltip();
    </script>
@endsection